apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<AZURE_CLIENT_ID>"
    keyvaultName: "kv-aks-prod-weu"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: payment-api-key
          objectType: secret
          objectVersion: ""
    tenantId: "<AZURE_TENANT_ID>"
  secretObjects:
  - secretName: app-vault-secrets
    type: Opaque
    data:
    - objectName: db-connection-string
      key: DB_CONNECTION_STRING
    - objectName: payment-api-key
      key: PAYMENT_API_KEY
