apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-data-pvc
  namespace: prod
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 32Gi
